# Generated by Django 2.2 on 2019-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('posColumn', models.CharField(max_length=30)),
                ('negColumn', models.CharField(max_length=30)),
                ('temporalOrder', models.FileField(upload_to='')),
            ],
        ),
    ]
