# Generated by Django 2.1.4 on 2019-12-23 10:24

from django.db import migrations, models
import mysite.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', validators=[mysite.core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='file',
            name='temporalOrder',
            field=models.FileField(upload_to='', validators=[mysite.core.validators.validate_file_extension]),
        ),
    ]
