# Generated by Django 2.2 on 2019-12-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
