# Generated by Django 2.2.9 on 2020-02-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191223_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='negColumn',
            new_name='decColumn',
        ),
        migrations.RemoveField(
            model_name='file',
            name='posColumn',
        ),
    ]
